### PR TITLE
Fix UnicodeEncodeError when scanning subtitles

### PR DESCRIPTION
**Pull request by qubic**
Fix the issuse that failed to load subtitle if the file path contain
non-ascii character

### CODE REVIEW

**Comment by alatas** [comment]
I have issues with paths contain non-ascii characters, tried this and its solved. thanks

**Comment by M0rtenB** [comment]
I too had this issue, though with adding folder.jpg to local tv shows.
I found that more instances of unicodize() needed an added .encode('utf-8') and am currently testing just adding it to the return-statement of helpers.unicodize(). It seems to work ok for now.

Thanks.

**Comment by M0rtenB** [comment]
Why close this without a fix?

**Comment by maxGreenblatt** [comment]
The fix was made in a different repo

**Pull request closed without merging**
