### PR TITLE
Season art support.

### PR DESCRIPTION
**Pull request by mmccurdy**
Add season art support.  GHI to follow with details about how this is not quite working yet.

### CODE REVIEW

**Comment by dettwild** [comment]
Hi, I just wanted to ask quickly if there is a reason that this change has never been merged into the LocalMedia.bundle? I understand there are only 2 lines to change and the server supports season artwork since more than a year. Therefore it would be great, if locally stored season fanart would also be pulled in;-).

**Comment by elan** [comment]
@mmccurdy ?

**Comment by mmccurdy** [comment]
No good reason, apparently. This repo is no longer active, but I made a PR on the PMS side so I'd expect this to land soon.

**Comment by dettwild** [comment]
Awesome, thanks @Elan and @mmccurdy (Mike) - happy to wait for the next PMS release.
Since you said this repo is no longer active, may I ask if my understanding is correct that all the Agents code is now contained and maintained in the main PMS repo, that one being a private repo and therefore the preferred way for community members to make proposals to be the forums? If indeed the case, perhas it would make sense to remove the user plexinc-agents the corresponding repos (like this one here) to avoid confusion for others that are finding this via search engines;-). Cheers

**Comment by mmccurdy** [comment]
This is (finally) fixed in master now... sorry for the delay :)

https://github.com/plexinc/plex-media-server/commit/a92017f2cb780e36a5094954be4d10bb90f7d80d

**Comment by dettwild** [comment]
Hi @mmccurdy, thanks very much for this. Unfortunatelly I can still not see the change working, even in PMS 1.3.4.3285
I expected to see the change in file
`...plexmediaserver\Binaries\Resources\Plug-ins-b46e0ea\LocalMedia.bundle\Contents\Code\localmedia.py` 
around line 180.
When I manually add the respective lines, e.g.
` search_tuples += [['season-?0?%s-fanart[-a-z]?' % metadata.index, metadata.art, config.IMAGE_EXTS, False]]` 
and then refresh a TV show that DOES have local Season-Art (named 'Season01-fanart.jpg' for example) , it all works fine.
Is it possible that the mentioned change was NOT yet merged into PMS Master?

**Pull request closed without merging**
